@startuml
abstract class Loader {
    - url : String
    + load(url: String)
}

class loadStream {
    - stream_url : String
    + load(stream_url: String)
    + getStreamData() : String
    + streamType : String
}

class loadFile {
    - file_path : String
    + load(file_path: String)
    + getFileData() : String
    + fileType : String
}

Loader <|-- loadFile : Inherits
Loader <|-- loadStream : Inherits
@enduml
