@startuml main_structure

entity Frame
entity Model
entity Position


Handler o-- Frame : has
Handler o-- Model : has
Handler o-- Position : has

abstract class Handler {
    + handle(result: String)
    + getPositionFromFrame() : Position
    + getFrameFromModel() : Frame
}

abstract class resolutionFixer {

}

class StreamResultHandler {
    + handle(result: String)
    + getFrameFromStream(streamResult: String) : Frame
    + getPositionFromFrame() : Position
    + getFrameFromModel() : Frame
}

class FileResultHandler {
    + handle(result: String)
    + getFrameFromFile(fileResult: String) : Frame
    + getPositionFromFrame() : Position
    + getFrameFromModel() : Frame
}

abstract class Loader {
    - url : String
    + load(url: String)
}

class StreamLoader {
    - stream_url : String
    + load(stream_url: String)
    + getStreamData() : String
    + streamType : String
}

class FileLoader {
    - file_path : String
    + load(file_path: String)
    + getFileData() : String
    + fileType : String
}

Loader <|-- FileLoader : Inherits
Loader <|-- StreamLoader : Inherits

Handler <|-- StreamResultHandler : Inherits
Handler <|-- FileResultHandler : Inherits

@enduml
