@startuml main_structure

entity Frame
entity Model
entity Position


HandlerInterface o-- Frame : has
HandlerInterface o-- Model : has
HandlerInterface o-- Position : has

abstract class HandlerInterface {
    + handle(result: String)
    + getPositionFromFrame() : Position
    + getFrameFromModel() : Frame
    + saveFile() : None
}

abstract class ResolutionFixerInterface {

}

class ResolutionFixer {

}

ResolutionFixerInterface <|-- ResolutionFixer : Inherits

abstract class UIInterface {
    
}

class NiceGUI {

}

UIInterface <|.. NiceGUI : Inherits

class StreamResultHandler {
    + handle(result: String)
    + getFrameFromStream(streamResult: String) : Frame
    + getPositionFromFrame() : Position
    + getFrameFromModel() : Frame
    + saveFile() : None
}

class FileResultHandler {
    + handle(result: String)
    + getFrameFromFile(fileResult: String) : Frame
    + getPositionFromFrame() : Position
    + getFrameFromModel() : Frame
    + saveFile() : None
}

abstract class LoaderInterface {
    - url : String
    + load(url: String)
}

class StreamLoader {
    - stream_url : String
    + load(stream_url: String)
    + getStreamData() : String
    + streamType : String
}

class FileLoader {
    - file_path : String
    + load(file_path: String)
    + getFileData() : String
    + fileType : String
}

StreamLoader o-- StreamResultHandler : uses
FileLoader o-- FileResultHandler : uses

LoaderInterface <|.. FileLoader : implements
LoaderInterface <|.. StreamLoader : implements
HandlerInterface o-- ResolutionFixer : uses
HandlerInterface <|.. StreamResultHandler : Inherits
HandlerInterface <|.. FileResultHandler : Inherits

NiceGUI *-- StreamLoader : uses
NiceGUI *-- FileLoader : uses
NiceGUI *-- ResolutionFixer : uses
NiceGUI *-- StreamResultHandler : uses
NiceGUI *-- FileResultHandler : uses








@enduml
