@startuml
abstract class Handler {
    + handle(result: String)
}

class streamResultHandler {
    + handle(result: String)
    + processStreamResult(streamResult: String)
}

class fileResultHandler {
    + handle(result: String)
    + processFileResult(fileResult: String)
}

Handler <|-- streamResultHandler : Inherits
Handler <|-- fileResultHandler : Inherits
@enduml